#!/usr/bin/env bash
# TRACE Graph — deploy one environment on this Mac.
#
#   scripts/deploy.sh dev|test|prod [--no-restart] [--reload-seed]
#
# env   branch    port   worktree
# dev   develop   8413   ~/workspace/trace-graph            (the main checkout)
# test  staging   8414   ~/workspace/trace-graph-envs/test  (git worktree)
# prod  main      8415   ~/workspace/trace-graph-envs/prod  (git worktree)
#
# Idempotent: creates the worktree if missing, checks out + fast-forwards the branch, installs
# python/node deps, builds the SPA, writes .env (keeping an existing access key), loads the seed
# claims when the database is empty, and kickstarts the launchd job.
set -euo pipefail

ENV_NAME="${1:-}"; shift || true
NO_RESTART=0; RELOAD_SEED=0
for arg in "$@"; do
  case "$arg" in
    --no-restart) NO_RESTART=1 ;;
    --reload-seed) RELOAD_SEED=1 ;;
    *) echo "unknown flag: $arg" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVS_ROOT="${TRACE_ENVS_ROOT:-$HOME/workspace/trace-graph-envs}"
TAXONOMY_URL="${TAXONOMY_BASE_URL:-http://localhost:8420}"
TAXONOMY_ENV_FILE="${TAXONOMY_ENV_FILE:-$HOME/workspace/meliaf-taxonomy-service/.env}"

case "$ENV_NAME" in
  dev)  BRANCH=develop; PORT=8413; WORKTREE="$REPO_ROOT" ;;
  test) BRANCH=staging; PORT=8414; WORKTREE="$ENVS_ROOT/test" ;;
  prod) BRANCH=main;    PORT=8415; WORKTREE="$ENVS_ROOT/prod" ;;
  *) echo "usage: scripts/deploy.sh dev|test|prod [--no-restart] [--reload-seed]" >&2; exit 2 ;;
esac
PUBLIC_URL="https://p${PORT}.synaptic.synapsis-analytics.com"
LABEL="com.synapsis.trace-graph-${ENV_NAME}"
say() { printf '\033[1m[deploy:%s]\033[0m %s\n' "$ENV_NAME" "$*"; }

# ---------------------------------------------------------------- 1. worktree on the right branch
if [ "$WORKTREE" != "$REPO_ROOT" ] && [ ! -d "$WORKTREE/.git" ] && [ ! -f "$WORKTREE/.git" ]; then
  say "creating worktree $WORKTREE on $BRANCH"
  mkdir -p "$(dirname "$WORKTREE")"
  git -C "$REPO_ROOT" show-ref --verify --quiet "refs/heads/$BRANCH" \
    || git -C "$REPO_ROOT" branch "$BRANCH" develop
  git -C "$REPO_ROOT" worktree add "$WORKTREE" "$BRANCH"
fi
cd "$WORKTREE"
CURRENT="$(git rev-parse --abbrev-ref HEAD)"
[ "$CURRENT" = "$BRANCH" ] || { say "checking out $BRANCH (was $CURRENT)"; git checkout "$BRANCH"; }
if git remote get-url origin >/dev/null 2>&1; then
  git fetch --quiet origin "$BRANCH" || true
  git merge --ff-only "origin/$BRANCH" 2>/dev/null || say "no fast-forward from origin/$BRANCH (local ahead or no remote branch) — continuing"
fi
say "at $(git rev-parse --short HEAD) on $BRANCH"

# ---------------------------------------------------------------- 2. python env
if [ ! -x .venv/bin/python ]; then
  say "creating .venv"
  "${PYTHON:-python3.12}" -m venv .venv
fi
./.venv/bin/pip install --quiet --upgrade pip >/dev/null
./.venv/bin/pip install --quiet -r requirements.txt
say "python deps ok ($(./.venv/bin/python -V))"

# ---------------------------------------------------------------- 3. .env (key is never regenerated)
mkdir -p data
KEY=""
[ -f .env ] && KEY="$(sed -n 's/^TRACE_ACCESS_KEY=\([^ #]*\).*/\1/p' .env | head -1)"
[ -z "$KEY" ] && [ -f data/access-key.txt ] && KEY="$(cat data/access-key.txt)"
# (openssl, not `tr </dev/urandom | head`: that pipeline dies on SIGPIPE under `set -o pipefail`)
[ -z "$KEY" ] && KEY="$(openssl rand -hex 20)"
printf '%s' "$KEY" > data/access-key.txt && chmod 600 data/access-key.txt
OPENAI_KEY=""
if [ -f "$TAXONOMY_ENV_FILE" ]; then
  OPENAI_KEY="$(sed -n 's/^OPENAI_API_KEY=\([^ #]*\).*/\1/p' "$TAXONOMY_ENV_FILE" | head -1)"
fi
cat > .env <<EOF
# generated by scripts/deploy.sh $ENV_NAME on $(date -u +%Y-%m-%dT%H:%M:%SZ) — do not commit
TRACE_ENV=$ENV_NAME
PORT=$PORT
TRACE_DB_PATH=data/trace.db
TRACE_DATA_DIR=data
TRACE_ACCESS_KEY=$KEY
TAXONOMY_BASE_URL=$TAXONOMY_URL
OPENAI_API_KEY=$OPENAI_KEY
TRACE_ASK_MODEL=${TRACE_ASK_MODEL:-gpt-5.5}
TRACE_PUBLIC_URL=$PUBLIC_URL
EOF
chmod 600 .env
say ".env written (access key in data/access-key.txt, mode 600)"

# ---------------------------------------------------------------- 4. frontend
if [ -d frontend ]; then
  ( cd frontend && npm ci --silent && npm run build --silent >/dev/null )
  say "frontend built ($(du -sh frontend/dist | cut -f1))"
fi

# ---------------------------------------------------------------- 5. seed the registry if empty
COUNT=0
if [ -f data/trace.db ]; then
  COUNT="$(./.venv/bin/python - <<'PY'
import os, sqlite3
try:
    con = sqlite3.connect("data/trace.db")
    print(con.execute("SELECT COUNT(*) FROM claims").fetchone()[0])
except Exception:
    print(0)
PY
)"
fi
if [ "$RELOAD_SEED" = "1" ]; then
  say "reloading the seed from scratch"; rm -f data/trace.db data/trace.db-wal data/trace.db-shm; COUNT=0
fi
if [ "${COUNT:-0}" -lt 1 ]; then
  say "loading the seed claim batches (this takes ~75 s)"
  ./.venv/bin/python -m app.cli load \
      data/claims/seed-porb.jsonl data/claims/seed-prms.jsonl data/claims/seed-cgspace.jsonl \
      data/claims/seed-toc.jsonl data/claims/seed-taxonomy.jsonl > data/last-load.json
  ./.venv/bin/python -m app.cli stats | head -8
else
  say "registry already holds $COUNT claims — not reloading (use --reload-seed to force)"
fi

# ---------------------------------------------------------------- 6. launchd
if [ "$NO_RESTART" = "0" ]; then
  "$WORKTREE/scripts/launchd-install.sh" "$ENV_NAME" >/dev/null
  launchctl kickstart -k "gui/$(id -u)/$LABEL"
  say "kickstarted $LABEL — waiting for /health"
  for i in $(seq 1 30); do
    sleep 1
    if curl -fsS "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then
      curl -fsS "http://127.0.0.1:$PORT/health" | ./.venv/bin/python -m json.tool | head -12
      say "UP on http://127.0.0.1:$PORT  ·  $PUBLIC_URL"
      exit 0
    fi
  done
  say "NOT healthy after 30 s — check $WORKTREE/data/server.log"; tail -20 data/server.log || true
  exit 1
fi
say "done (no restart requested)"
